#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Caleb Schoepp"
email = "caleb.schoepp@gmail.com"

[ui]
diff-editor = ":builtin" # The builtin isn't bad once you learn the hotkeys
editor = "vim"

[template-aliases]
# Only show the shortest possible name for change IDs
"format_short_change_id(id)" = "id.shortest()"

# Configure signing backend as before, but lazily signing only on push.
[signing]
behavior = "drop"
backend = "gpg"
key = "FEA095EAF754EABA"
[git]
sign-on-push = true

# Sign off commits with Authored-by trailers
[templates]
commit_trailers = 'format_signed_off_by_trailer(self)'

[revset-aliases]
"closest_pushable(to)" = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'
"closest_bookmark(to)" = 'heads(::to & bookmarks())'

[aliases]
# Tug the closest bookmark to the closest pushable commit
# TODO: Consider improving my tug alias as per https://andre.arko.net/2025/10/15/jj-part-4-configuration/
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "closest_pushable(@)"]

# TODO: Consider making "commits" you've already pushed immutable https://zerowidth.com/2025/jj-tips-and-tricks/#immutable-branches
# e.g.
# [revset-aliases]
# # set all remote bookmarks (commits pushed to remote branches) to be immutable
# 'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"
