#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Caleb Schoepp"
email = "caleb.schoepp@gmail.com"

[ui]
diff-editor = ":builtin" # The builtin isn't bad once you learn the hotkeys
editor = "vim"
default-command = "sl" # Run this when you type plain `jj`

[template-aliases]
# Only show the shortest possible name for change IDs
"format_short_change_id(id)" = "id.shortest()"

# Configure signing backend as before, but lazily signing only on push.
[signing]
behavior = "drop"
backend = "gpg"
key = "FEA095EAF754EABA"
[git]
sign-on-push = true

# Sign off commits with Authored-by trailers
[templates]
commit_trailers = 'format_signed_off_by_trailer(self)'

[revset-aliases]
"closest_pushable(to)" = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'
"closest_bookmark(to)" = 'heads(::to & bookmarks())'

[aliases]
c = ["commit"]
ci = ["commit", "--interactive"]
e = ["edit"]
# Bring the closest bookmark up to the closest pushable change
tug = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", ""]
# Status and log combined
sl = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail

jj status --color=always | perl -ne '
  our $stop;
  my $plain = $_;
  $plain =~ s/\\e\\[[0-9;]*m//g;
  $stop = 1 if $plain =~ /^Working copy\\s+\\(@\\)\\s*:/;
  print $_ unless $stop;
'
jj log --color=always
""", ""]

# TODO: Consider making "commits" you've already pushed immutable https://zerowidth.com/2025/jj-tips-and-tricks/#immutable-branches
# e.g.
# [revset-aliases]
# # set all remote bookmarks (commits pushed to remote branches) to be immutable
# 'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"

# TODO: Config inspiration https://github.com/indirect/dotfiles/blob/main/private_dot_config/private_jj/config.toml
# TODO: Config inspiration https://gist.github.com/thoughtpolice/8f2fd36ae17cd11b8e7bd93a70e31ad6
# TODO: Config inspiration https://gist.github.com/pksunkara/622bc04242d402c4e43c7328234fd01c
