#:schema https://docs.jj-vcs.dev/latest/config-schema.json

user.name = "Caleb Schoepp"
user.email = "caleb.schoepp@gmail.com"

ui.diff-editor = ":builtin" # The builtin isn't bad once you learn the hotkeys
ui.editor = "vim"

# Only show the shortest possible name for change IDs
template-aliases."format_short_change_id(id)" = "id.shortest()"

# Configure signing backend as before, but lazily signing only on push.
signing.behavior = "drop"
signing.backend = "gpg"
signing.key = "FEA095EAF754EABA"
git.sign-on-push = true

# Sign off commits with Authored-by trailers
templates.commit_trailers = 'format_signed_off_by_trailer(self)'
